config/routes.rb
Tracker::Application.routes.draw do
  
  #===============================================================
  #       DEVISE/USERS 
  #===============================================================
  resources :users
  devise_for :users, :skip => [:registrations, :sessions]
  as :user do
    get "/login"     => "devise/sessions#new",      :as => :new_user_session
    post "/login"    => "devise/sessions#create",   :as => :user_session
    delete "/logout" => "devise/sessions#destroy",  :as => :destroy_user_session
  end
  resources :organizations do
    get 'admin_panel' =>  'organizations#admin', as: :admin_panel
  end

	
  #===============================================================
  #         STATIC
  #===============================================================
  root 'static_pages#home'
  get 'contact'  => 'static_pages#contact'
  get 'help'     => 'static_pages#help'  
  get 'about'    => 'static_pages#about'   

  #===============================================================
  #       SEARCH/DATE
  #===============================================================
  resources :search_results, only: [:search]
    get '/search_results' => 'search_results#search'

  resources :order_types do 
    get 'archive' => 'order_types#archive'

    # resources :date, only: [:show_year, :show_month, :show_day]

    get "date/:year/:month/:day" => "dates#show_day", as: :show_day
    get 'date/:year/:month'      => 'dates#show_month', as: :show_month
    get 'date/:year'             => 'dates#show_year', as: :show_year
    
    resources :orders
  end

end

app/views/layouts/nav/_new_order.html.erb
<div class="new_order" style="margin-top: .5em">
  <% unless @order_type.nil? || @order_type.id.nil? %>
  <%= link_to 'Enter new Order', "/order_types/#{@order_type.id}/orders/new",
    class: "btn btn-primary" %>
  <% else %>
    <button type="button" class="btn btn-primary" disabled="disabled">Enter new Order</button>
   <% end %>

</div>

app/views/layouts/nav/_search.html.erb
<div class="panel panel-default"style="margin: 0px;margin-top: 0">
  <div class="panel-heading">
    <h4 class="panel-title">
      <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
        Search
      </a>
    </h4>
  </div>
  <div id="collapseThree" class="panel-collapse collapse in">
    <div class="panel-body" style="padding: 0;">
      <div class="list-group">
        <% unless @order_type.nil? || @order_type.id.nil? %>
          <h3 class="panel-title" style="padding: .5em;">Orders by Month</h3>
          <% show_orders_by_month.each do |date| %>
            <a class="list-group-item" 
            href="<%= order_type_show_month_path(@order_type.id, date.year, date.month) %>">

              <span class="glyphicon glyphicon-calendar"></span>
              <%= "#{Date::MONTHNAMES[date.month]} #{date.year}" %>
            </a>
          <% end %>
            <a class="list-group-item" href="<%= order_type_archive_path(@order_type)%>">
              <span class="glyphicon glyphicon-list-alt"></span>
              Show Archive
            </a>
        <% end %>
				<br>
          <div style="postion:relative">
              <%= form_tag search_results_path, method: :get, class:"search-form" do %>
                <%= text_field_tag :search, params[:search], class:"form-control",style:"width: 70%; float:left", placeholder:"Enter Order ID" %>

                <button style="width: auto;float:right"type="submit" class="btn btn-default">
                  <span style="padding-right: 0;" class="glyphicon glyphicon-search"></span>
                </button>

              <% end %>
          </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/nav/_signed_out.html.erb
<div id="login-panels">
  <div style="top:20px;" class="panel panel-group" id="accordion nav_bar">
  	<div class="panel panel-default"style="margin: 0px;margin-top: 0">
      <div class="panel-heading">
        <h4 class="panel-title">Login</h4>
      </div>
      <div class="panel-body">
        <%= render 'devise/sessions/new' %>
      	<%#= link_to "Login", new_user_session_path %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/nav/_template.html.erb
<div class="panel panel-default"style="margin: 0px; margin-top: 0">
  <div class="panel-heading">
    <h4 class="panel-title">
      <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
        <% if @order_type.nil? || @order_type.id.nil?%>
					Select Template
				<% else %>
					<%= @order_type.title %>
				<% end %>	
      </a>
    </h4>
  </div>
  <div id="collapseTwo" class="panel-collapse collapse in">
    <div class="panel-body"style="padding: 0;">
      <div class="list-group">	
				<% current_user.order_types.each do |type| %>
				<% unless type == @order_type %>
        <%= link_to "<span class='glyphicon glyphicon-tasks'></span>#{type.title}".html_safe, type, class: "list-group-item" %>
				<% end %>
				<% end %>
        <a class="list-group-item" href="<%= new_order_type_path %>">
          <span class="glyphicon glyphicon-edit"></span>
          Create New
        </a>
			</div>
    </div>
  </div>
</div>

app/views/layouts/nav/_user.html.erb
<div class="panel panel-default"style="margin: 0px;margin: 0px">
  <div class="panel-heading">
    <h4 class="panel-title">
      <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
        <%= current_user.full_name %>
      </a>
    </h4>
  </div>
  <div id="collapseOne" class="panel-collapse collapse in">
    <div class="panel-body"style="padding: 0;">
      <div class="list-group">
        <% if current_user.organization.nil? %>
        <%= link_to '<span class="glyphicon glyphicon-briefcase"></span>Create Organization'.html_safe, new_organization_path, class: "list-group-item" %>
        <% else %>
  			<%= link_to '<span class="glyphicon glyphicon-briefcase"></span>Organization'.html_safe, current_user.organization, class: "list-group-item" %>
        <% end %>
  
        <a href="/users/<%= current_user.id%>" class="list-group-item">
          <span class="glyphicon glyphicon-user"></span>
          Profile
        </a>
        <a class="list-group-item" href="<%= edit_user_path(current_user.id) %>">
          <span class="glyphicon glyphicon-cog"></span>
          Settings
        </a>
        <%= link_to '<span class="glyphicon glyphicon-log-out"></span>Log Out'.html_safe, destroy_user_session_path, class: "list-group-item", method: :delete %>
      </div>
    </div>
  </div>
</div>