config/routes.rb
Tracker::Application.routes.draw do
  
  #===============================================================
  #       DEVISE/USERS 
  #===============================================================
  resources :users
  devise_for :users, :skip => [:registrations, :sessions]
  as :user do
    get "/login"     => "devise/sessions#new",      :as => :new_user_session
    post "/login"    => "devise/sessions#create",   :as => :user_session
    delete "/logout" => "devise/sessions#destroy",  :as => :destroy_user_session
  end
  resources :organizations do
    get 'admin_panel' =>  'organizations#admin', as: :admin_panel
  end

	
  #===============================================================
  #         STATIC
  #===============================================================
  root 'static_pages#home'
  get 'contact'  => 'static_pages#contact'
  get 'help'     => 'static_pages#help'  
  get 'about'    => 'static_pages#about'   

  #===============================================================
  #       SEARCH/DATE
  #===============================================================
  resources :search_results, only: [:search]
    get '/search_results' => 'search_results#search'

  resources :order_types do 
    get 'archive' => 'order_types#archive'

    # resources :date, only: [:show_year, :show_month, :show_day]

    get "date/:year/:month/:day" => "dates#show_day", as: :show_day
    get 'date/:year/:month'      => 'dates#show_month', as: :show_month
    get 'date/:year'             => 'dates#show_year', as: :show_year
    
    resources :orders
  end

end

app/controllers/dates_controller.rb
class DatesController < ApplicationController

  before_filter :authenticate_user!
  before_action :set_order_type
  before_action :validate_user
  before_action :set_date, only: [:show_year, :show_month, :show_day]
  after_filter :clear_gon, only: [:show_month]

  def show_day
    time_range = (@date.beginning_of_day.in_time_zone..@date.end_of_day.in_time_zone)
    @orders = @order_type.orders.date(time_range)
    @order_error_status = @orders.group_by(&:error)
  end

  def show_month
    time_range = (@date.beginning_of_month.to_date..@date.end_of_month.to_date - 1)
    @orders = @order_type.orders.date(time_range)
    @orders_by_day = @orders.group_by {|x| x.created_at.day }
    @order_error_status = @orders.group_by(&:error)
    @errors = @orders.breakdown
    gon_data
  end

  def show_year
    redirect_to order_type_archive_path(@order_type.id)
  end

  def pie_chart_data(opt)
    arr = []
    opt.each_pair { |key, value| arr << [key, opt[key].values.sum] }
    return arr
  end

  def gon_data
    gon.chart_data = pie_chart_data(@errors)
    gon.date = @date.strftime("%B %Y")
    gon.test = @errors.keys
  end

  def clear_gon
    gon.clear
  end

private

	def set_order_type
    @order_type = OrderType.find(params[:order_type_id])
  end
  
  def set_date
    validate_year
    validate_month
    return_date    
  end

  def validate_year
    if params[:year].nil? || params[:year].to_i == 0
      params[:year] = @today.year
      invalid_date
    end
  end

  def validate_month
    if params[:month].to_i < 1 || params[:month].to_i > 12
      params[:month] = @today.month
      invalid_date
    end
  end

  def return_date
    date = [params[:year], params[:month], params[:day]]
          .map {|p| p ||= '1' }
    if Date.valid_date? date[0].to_i, date[1].to_i, date[2].to_i
      @date = Date.parse("#{date[2]}.#{date[1]}.#{date[0]}")
    else
      @date = @today
      invalid_date
    end
  end

  def invalid_date
    flash[:warning] = "Invalid date"
  end
  
  def validate_user
    unless @order_type.organization == current_user.organization
      redirect_to root_url
      flash[:warning] = "You do not have permission to access that"
    end
  end

end

app/views/dates/_bar_charts.html.erb
<% @errors.each_pair do |category, tasks| %>	
	<table id="<%= category.downcase.gsub(/ /,"_") %>-container" style="display:none">
		<th colspan="2"><%=category%></th>
		<% @errors[category].each_pair do |task, value| %>
			<tr>
				<td><%=task%></td>
				<td><%=value%></td>
			</tr>
		<% end %>
	</table>		

<div class="bar_chart <%=category.downcase.gsub(/ /,"_") %>-container" style="display:none">
</div>
<% end %>

app/views/dates/_breakdown.html.erb
<h3>
<% if @orders.count > 0 %>
	<strong>Quality</strong> 
	<% if @order_error_status[false].nil? %>
	0
	<% else %>
	<%= @order_error_status[false].size %>
	<% end %>
	/<%=@orders.size%> | <%= quality %>%
<% else %>
	<strong> No Data</strong>
<% end %>
</h3>

app/views/dates/_calendar.html.erb
<div class="month">
<%= calendar(@date) do |date| %>
  <% if date.month == @date.month %>
	  <div class="day"><%= link_to date.day, "#{date.month}/#{date.day}" %></div>
	  	<div class="inner">
			<% if @orders_by_day[date.day].nil? %>
				No<br>Orders
			<% else %>
				<%= breakdown(date.day)[false] || 0 %>/<%= @orders_by_day[date.day].size %>
				<br>
				<strong><%= quality_by(date.day) %>%</strong>
			</div>
			<% end %>
	<% end %>
<% end %>
</div>

<script>
	autoResize();
	$(window).resize(function() {
		autoResize();
	});
</script>

app/views/dates/_chart.html.erb
<script>
  $(document).ready(function() { 
    pieChart();

    var categories = gon.test;
		for(i = 0; i < categories.length; i++){
			name = categories[i].toLowerCase().replace(' ', '_')+"-container";
			barChart(name.toString());
		}
  });

</script>

app/views/dates/_list.html.erb
<div class="breakdown well list-group" >
	<% @errors.each_pair do |category, tasks| %>
		<div id="<%= category.downcase.gsub(/ /,"_") %>-container">
			<a href="#" class="list-group-item active">
				<%= category %>
			</a>
				<% @errors[category].each_pair do |task, value| %>
					<li class="list-group-item">
						<span class="badge"><%= value %></span>
						<%= task %>
					</li>
				<% end %>
		</div>
	<% end %>
</div>

app/views/dates/_order.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= link_to "##{order.order_name}", order_type_order_path(@order_type.id, order.id) %></div>
  <div class="panel-body">
    <div style="padding-bottom:.5em">Proofed: <%= order.user.full_name %></div>
  <% if order.error == false %>
    <span style="font-weight:700; color: #3c763d">
      <span class="glyphicon glyphicon-ok-circle"></span> No Errors
  </div>
  <% else %>
    <table style="border: none">
      <th style="color:#a94442"><span class="glyphicon glyphicon-remove-circle"></span>
        <%= pluralize(order.show_errors.values.flatten.count, "Error") %>
      </th>
      <th>Notes</th>
      <tr>
        <td style="width: 50%">
          <ol>
            <% order.show_errors.each_pair do |key, value| %>
              <% value.each do |task| %>
                <li><strong><%= key %>: </strong><%= task %></li>
              <% end %>
            <% end %>
          </ol>
        </td>
        <td style="width: 50%">
          <div style="border: 1px solid #8a6d3b; margin-top: 1em; padding: .5em; background-color:#fcf8e3; color: #8a6d3b"> 
            <% if order.note.empty? %>
              <p>N/A</p>
            <% else %>
              <%= simple_format order.note %>
            <% end %>
          </div>
        </td>
      </tr>
    </table>
  </div>
  <% end %>
  <div class="panel-footer" style="padding: 5px 15px; text-align: right">
    <h6 style="margin:0">
      <%#= link_to 'Edit', "/order_types/#{@order_type.id}/orders/#{order.id}/edit" %> 
      <%= link_to 'Edit', edit_order_type_order_path(@order_type.id, order.id) %>
      | 
      <%= link_to 'Delete', order_type_order_path(@order_type.id, order.id), method: :delete, data: { confirm: 'Are you sure?' } %></h6>
  </div>
</div>
  

app/views/dates/show_day.html.erb
<div style="width:100%">
<h2> Listing Orders for <%= @date.strftime("%x") %></h2>
<%= render 'breakdown' %>
</div>
<div class="with_errors">
		<ol>
	    <% @orders.each do |order| %>
	      <li><%= render order %></li>
	    <% end %>
	  </ol>
</div>

app/views/dates/show_month.html.erb
<%= include_gon %>
<div id="orders">
	<h2 style="padding-top:0">
		<%= @order_type.title %> for <%= @date.strftime("%B %Y") %> 
	</h2>
	<%= render 'calendar' %>
</div>

<div style="margin: 0; margin-top: 1em" class="panel panel-default" >
  <div class="panel-heading"> 
  	<%= render 'breakdown' %>
  </div>
		<div class="panel-body">
		<% if @orders.count > 0 %> 
			<div id="chart" class="chart"></div>
			<div id ="render-chart">
				
				<%= render 'bar_charts' %>
			</div>
			<%= render 'chart' %>
		<% end %>
		</div>
		
</div>