config/routes.rb
Tracker::Application.routes.draw do
  
  #===============================================================
  #       DEVISE/USERS 
  #===============================================================
  resources :users
  devise_for :users, :skip => [:registrations, :sessions]
  as :user do
    get "/login"     => "devise/sessions#new",      :as => :new_user_session
    post "/login"    => "devise/sessions#create",   :as => :user_session
    delete "/logout" => "devise/sessions#destroy",  :as => :destroy_user_session
  end
  resources :organizations do
    get 'admin_panel' =>  'organizations#admin', as: :admin_panel
  end

	
  #===============================================================
  #         STATIC
  #===============================================================
  root 'static_pages#home'
  get 'contact'  => 'static_pages#contact'
  get 'help'     => 'static_pages#help'  
  get 'about'    => 'static_pages#about'   

  #===============================================================
  #       SEARCH/DATE
  #===============================================================
  resources :search_results, only: [:search]
    get '/search_results' => 'search_results#search'

  resources :order_types do 
    get 'archive' => 'order_types#archive'

    # resources :date, only: [:show_year, :show_month, :show_day]

    get "date/:year/:month/:day" => "dates#show_day", as: :show_day
    get 'date/:year/:month'      => 'dates#show_month', as: :show_month
    get 'date/:year'             => 'dates#show_year', as: :show_year
    
    resources :orders
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
	has_many :order_types
	has_many :users
	has_many :orders, :through => :order_types

	validates :title, :presence => true
	
	before_save {self.title = title.split.map {|x| x.capitalize }.join(" ") }

	def admins
		users.select {|x| x.admin}
	end

	def inactive_users
		users.reject {|x| x.active}
	end

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
	before_filter :authenticate_user!
	before_action :validate_admin, except: [:index, :show]
	before_action :no_org?, only: [:new]
	before_action :validate_org, except: [:new, :create]
	
	def index
		redirect_to @organization
	end

	def admin
	end
	
	def edit
	end

	def update
    if @organization.update(organization_params)
      flash[:success] = "Organization was successfully updated"
      redirect_to @organization  
    else
      render action: 'edit'
    end
  end

	def show
		if @organization.nil?
			redirect_to new_organization_path
		end
		@users = @organization.users.reorder('last_name ASC').page(params[:page]).per_page(10)
		@order_types = @organization.order_types
	end

	def new
		@organization = Organization.new
	end

	def create
		@organization = Organization.new(organization_params)
   		if @organization.save
    		current_user.update_attributes(organization_id: @organization.id)
    		flash[:success] = "Organization created"
      	redirect_to @organization
    	else
      render action: 'new'
    end
	end

	def destroy
	end

	private

	def no_org?
		if @organization != nil
			redirect_to root_path
			flash[:warning] = "You already belong to an organization"
		end
	end

	def validate_org
		if signed_in? && @organization.nil?
			redirect_to new_organization_path
			flash[:warning] = "Please create an organization"
		end
	end

	def validate_admin
		unless current_user.admin?
			redirect_to root_path
			flash[:warning] = "You do not have the required permission."
		end
	end

	def organization_params
		params.require(:organization).permit(:title)
	end
end

app/views/organizations/_form.html.erb
<%= form_for @organization do |f| %>
	<%= render 'layouts/error_messages', object: f.object %>
	
	<div class="form-inline form-org" role="form">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
	</div>

	<div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/organizations/admin.html.erb
<div class="panel panel-primary">
	<div class="panel-heading" style="border-radius:0">
		<h4>Administrative Controls</h4>
	</div>
  <div class="panel-body">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#admin-all" data-toggle="tab">All</a></li>
      <% ['org','templates','users'].each do |partial| %>
        <li>
          <a href="#admin-<%=partial%>" data-toggle="tab">
            <%=partial.capitalize%>
          </a>
        </li>
      <% end %>
    </ul>

<!-- Tab panes -->
    <div class="tab-content">
      <div class="tab-pane active" id="admin-all">
      	<p style="padding-top:1em">
          Modify elements of your organization. Change or remove templates or users, and rename your organization.
        </p>
        
        <% ['org','templates','users'].each do |partial| %>
          <%= render "organizations/admin/#{partial}" %>
        <% end %>

      </div>

      <% ['org','templates','users'].each do |partial| %>
        <div class="tab-pane" id="admin-<%=partial%>">
      	 <%= render "organizations/admin/#{partial}" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/organizations/edit.html.erb
<h2>Editing <%= @organization.title %><h2>
<%= render 'form' %>

app/views/organizations/index.html.erb
Nothing to see here, move along now.

app/views/organizations/new.html.erb
<h2> Create Organization</h2>
<%= render 'form' %>

app/views/organizations/show.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">
		<h4><%= @organization.title %></h4>
	</div>

	<div class="panel-body">
		<% if current_user.admin? %>
			<%= link_to 'Admin Controls', organization_admin_panel_path(@organization) %>
		<% end %>

		<h4>Users</h4>
			<%= render 'users/index' %>

		<h4>Templates</h4>		
			<% @organization.order_types.each do |type| %>
				<%= link_to type.title, order_type_path(type) %><br>
			<% end %>

	</div>
</div>