config/routes.rb
Tracker::Application.routes.draw do
  
  #===============================================================
  #       DEVISE/USERS 
  #===============================================================
  resources :users
  devise_for :users, :skip => [:registrations, :sessions]
  as :user do
    get "/login"     => "devise/sessions#new",      :as => :new_user_session
    post "/login"    => "devise/sessions#create",   :as => :user_session
    delete "/logout" => "devise/sessions#destroy",  :as => :destroy_user_session
  end
  resources :organizations do
    get 'admin_panel' =>  'organizations#admin', as: :admin_panel
  end

	
  #===============================================================
  #         STATIC
  #===============================================================
  root 'static_pages#home'
  get 'contact'  => 'static_pages#contact'
  get 'help'     => 'static_pages#help'  
  get 'about'    => 'static_pages#about'   

  #===============================================================
  #       SEARCH/DATE
  #===============================================================
  resources :search_results, only: [:search]
    get '/search_results' => 'search_results#search'

  resources :order_types do 
    get 'archive' => 'order_types#archive'

    # resources :date, only: [:show_year, :show_month, :show_day]

    get "date/:year/:month/:day" => "dates#show_day", as: :show_day
    get 'date/:year/:month'      => 'dates#show_month', as: :show_month
    get 'date/:year'             => 'dates#show_year', as: :show_year
    
    resources :orders
  end

end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error explanation">
		<div class="alert alert-danger error-message">
			<h4><span style ="width:20px"class="glyphicon glyphicon-exclamation-sign"></span>
				Could not <%= params[:action] %> this <%= object.class.name.downcase %> due to  <%= pluralize(object.errors.count, "error") %>:</h4>
			<ul style="margin-left: 1em">
			<% object.errors.full_messages.each do |msg| %>
				<li> <%= msg %></li>
			<% end %>
			</ul>	
		</div>
	</div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
	<div class="<%="alert alert-#{key}"%>">
		<span class="glyphicon glyphicon-<%=alert_icons[key]%>" style="font-size: 15px"></span>
		<%= value %>
	</div>
<% end %>

app/views/layouts/_footer.html.erb
<div>
	<ul class="list-inline" style="list-style-type:circle">
		<li style="color:#777">2015 John Calvin</li>
		<li><%= link_to 'About', about_path %></li>
		<li><%= link_to 'GitHub', 'https://github.com/jdcalvin/error_tracking' %></li>
		<li><%= mail_to 'calvjd@gmail.com', 'Email' %></li>
	</ul>
</div>

app/views/layouts/_header.html.erb
	<div id="side_nav_toggle" class="pull-left">
		<button type="button" class="btn btn-default btn-menu" data-toggle="offcanvas">
			<span class="glyphicon glyphicon-th-list"></span>
			Menu
		</button>
			
        <%= link_to '<span class="glyphicon glyphicon-home"></span>'.html_safe, root_path %>

        <%= link_to '<span class="glyphicon glyphicon-question-sign"></span>'.html_safe, help_path %>

        <%= link_to '<span class="glyphicon glyphicon-comment"></span>'.html_safe, contact_path %>  
        <% if @organization %>
  			   <%= link_to '<span class="glyphicon glyphicon-dashboard"></span>'.html_safe, organization_admin_panel_path(@organization) %>
         <% end %>
			</div>  		
	</div>

app/views/layouts/_navbar.html.erb
<div id="nav_menu">
  <table style="border:none">
    <tr>
      <td><%= link_to '<span class="glyphicon glyphicon-home"></span>'.html_safe, root_path %></td>
  		<td><%= link_to '<span class="glyphicon glyphicon-question-sign"></span>'.html_safe, help_path %></td>
  		<td><%= link_to '<span class="glyphicon glyphicon-comment"></span>'.html_safe, contact_path %></td>

  		<% if @organization %>
        <td><%= link_to '<span class="glyphicon glyphicon-dashboard"></span>'.html_safe, organization_admin_panel_path(@organization) %></td>
      <% end %>
		</tr>
	</table>
</div>

<% if user_signed_in? %>

  <div class="panel panel-group" style="margin-top: 0em; margin:0px;" 
		id="accordion nav_bar">
		<% ['user', 'template', 'search'].each do |f| %>
			<%= render "layouts/nav/#{f}" %>  
		<% end %>
  </div>
    <%= render 'layouts/nav/new_order' %>

<% else %>
  <%= render 'layouts/nav/signed_out' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= favicon_link_tag 'favicon-check.ico' %>
  <title>Error Tracker
  	<% unless @order_type.nil? %>
  	| <%= @order_type.title %>
  	<% end %>
  </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header'  %>	
		<div class="container">
			<div class="row row-offcanvas row-offcanvas-left">
				<!--NAV-->
				<div class="col-sm-3 sidebar-offcanvas" id="side">			
					<%= render 'layouts/navbar' %>
				</div>

				<!--CONTENT-->
				<div class="col-xs-12 col-sm-9" id="content">
					<div class="panel panel-body" id="content-panel" style="border:1px solid #dddddd; margin: 0px; padding:.5em; min-height: 500px">
						<%= render 'layouts/flash' %>
						<%= yield %>
					</div>
				</div>

			</div>
		</div>

		<footer>
			<%= render 'layouts/footer' %>
		</footer>
</body>
</html>